mapzen/documentation

config/search.yml

Add leaflet plug-in tutorial
Change the source to pelias org

Add tutorial topic, switch to pelias org for source

---

Makefile
config/vector-tiles.yml

* source vector tile service docs from real repo, woo!
* upgrade assumptions in Makefile

source vector tile service docs from real repo

---

config/matrix.yml

I merged the valhalla changes to its master and renamed a file in the TOC.

update matrix help branch

---

Makefile

Add the new metro extracts topics that are in master to the prd branch

Add metro extracts topic to prd

---

Makefile
run-checklist.py

Eliminate full styleguide download

---

circle.yml

Copy everything to Circle artifacts directory so Precog can see it.
Closes #114.

Make Precog-compatible

---

Makefile
config/vector-tiles.yml

* freeze vector tiles at v0.8.0-beta1 (not master), before they're really updated for v0.8
* reorder sidebar order to promote Layers

Nvkelso/nvkelso/tiles v0.8.0 beta1

---

run-checklist.py

Think it needs to look for Layers section first.

Updated Vector Tiles test

---

src-index/index.md
theme/base.html

use assets from styleguide instead of blog

---

Makefile

WAIT TO MERGE UNTIL v0.9 TILES ARE LIVE!

update docs for v0.9 vector tiles

---

config/tangram.yml

Also alphabetize the tech reference section

Add missing md files to tangram help

---

requirements.txt
run-checklist.py

Use configured titles instead of hard-coded strings in all tests

---

config/tangram.yml

This reverts commit 1ab95d20cb3e4b74f311a7f4078cfd830ec8bbfd, reversing changes made to a55f953b4f0609214f911330157005b6006b69a8.
This should get us back to a passing master branch, then we can re-do PRs #130 and #133 with rebased commits.

Revert pull request #130

---

config/tangram.yml
run-checklist.py

Reorganize Tangram docs

---

config/tangram.yml

...from syntax reference to concept overviews.

move yaml.md

---

theme/base.html
theme/search-form.html

resolves #144 
I removed the search.js file from base.html and replaced the input field - I wasn't sure if other things on the site were using search-modal.html, or the search code in js/base.js. Happy to remove all of that if people want!

144 binx search box

---

theme/search-form.html

pulling out the style tag

---

README.md

add info about changing the branch to readme

---

Makefile

Updated fragments URLs

---

Makefile

Removed --wildcards from tar invocation, it seems to be the default

---

src-index/index.md

related to https://github.com/mapzen/mapzen-docs-generator/pull/162

moving forward to new class name

---

config/tangram.yml

Preview here: https://precog.mapzen.com/mapzen/mapzen-docs-generator/meetar/fonts/documentation/tangram/fonts/
Ready to merge pending review

add fonts.md

---

Makefile
config/optimized.yml
run-checklist.py
src-index/index.md

Created a new section for the new service.

Added Optimized Routing documentation

---

docs/index.md

Add info about optimized route: limits and API keys
Move elevation to data to match docs landing page

Update rate limits for optimized route

---

Makefile
config/mobility.yml
setup-renames.py

Setup way to rename files and configured Mobility section

---

config/tangram.yml

pending https://github.com/tangrams/tangram-docs/pull/135

add Tangram Overview

---

docs/index.md

Trying to answer some of the common questions -- namely, what happens when you exceed the limits, and adding in info on caching.

Updates for the rate limits page

---

docs/index.md

just removed the turn-by-turn, otherwise ready for unified keys update

unified keys update

---

theme/base.html

Keeps the in-docs navigation together, and moves the external link down below.

Moved "Edit this page" below pagination links

---

docs/index.md

fixes #195 
to clarify that it's formatted as`&api_key= `

add api_key= to steps

---

docs/index.md

add anchor refs for Tangram and Vector Tile map products

---

config/search.yml

to be pushed concurrently with https://github.com/pelias/pelias-doc/pull/146
- changes hierarchy of Search TOC
- adds redirect for get started page
- removes get started page because of redundancy

Update search docs

---

config/android.yml

Put new topics and placeholders in to TOC. We can rearrange the order, topic naming, and so on without causing trouble for the URL.  
cc @ecgreb

Add new Android topics

---

Makefile
config/ios.yml
run-checklist.py
src-index/index.md

This adds iOS to the documentation site, as a coming soon placeholder.
cc @ecgreb @msmollin @mjcunningham

Add iOS section

---

Makefile
config/vector-tiles.yml

- Minor terrain tile doc edits from @meetar 
- Medium vector tiles docs from @kkowalsky for display vector tiles
- Add significant migration doc from @rmglennon vector tiles

Update to v1.0.0-docs3 of vector tiles and terrain tiles

---

Makefile

- related to https://github.com/mapzen/website/issues/1255

using new nav for docs page

---

Makefile

- related : https://github.com/mapzen/website/issues/1361

fetching navbar.html as navbar has a new style

---

docs/overview/index.md

Fixes https://github.com/mapzen/documentation/issues/254

change & to ? for the API key parameter example

---

circle.yml

- related mapzen/website#1410
- shouldn't affect prod in anyway

separated staging deployment

---

theme/base.html

added new sets of favicons

---

config/tangram.yml
theme/nav-sub.html

- Handled sub-category passed from config ( I am not sure how scalable this solution would be. Is there anything like this case on docs that I should checkl @kkowalsky ?)
- closes #https://github.com/mapzen/documentation/issues/276
- I would appreciate second eyes @meetar !

fixed toc on tangram docs

---

theme/toc.html

- just added comments for next time I touch toc on docs page

added comments for next time

---

config/tangram.yml

Blocks https://github.com/mapzen/website/pull/1591

Add iOS walkthrough for Tangram

---

config/ios.yml

Depends on this PR merging: https://github.com/mapzen/ios/pull/255

Add more ios documentation

---

docs/overview/billing.md

remove this note per @randymeech

Update billing statement

---

docs/overview/account-settings.md
docs/overview/billing.md
docs/overview/rate-limits.md

All of the functions and billing are real. Removing the note with the effective date.

Remove effective date from notes on billing pages

---

config/mapzen-js.yml

Adds the routing docs for mapzen.js

Add routing to table of contents for mapzen.js

---

config/cartography.yml

- Add new Themes page to table of contents
- Move existing API reference page in TOC down a few above Versions
Related Cartography docs PR was approved by @kkowalsky on Monday: https://github.com/tangrams/cartography-docs/pull/28.

Update carto docs with Themes

---

config/vector-tiles.yml

Will also pick up changes in https://github.com/tilezen/vector-datasource/pull/1288/.

Add HTTP status codes page

---

docs/overview/rate-limits.md

To correspond with announcement: https://mapzen.com/blog/more-flex/
Please double-check my numbers!

Update mobility and elevation limits

---

config/search.yml

This adds a new topic to the help for search, following https://github.com/pelias/pelias-doc/pull/204

Add common workflows topic to search help

---

docs/overview/rate-limits.md

Automobile and similar costing options are 400 km; others are still 200 km.
https://github.com/valhalla/valhalla/pull/758/
https://mapzen.com/documentation/mobility/release-notes/#release-date-2017-06-12-valhalla-226

Update Matrix distance limits

---

docs/overview/account-settings.md
docs/overview/billing.md

A few updates to the billing overview documentation.
- adds content for the ability to add your name, address, and tax ID to your account and invoice
- updates a section about the dashboard to discuss the account summary and billing history functions.

add docs for billing info, name, and invoices

---

config/android.yml

Creates new section for LOST docs
Dependent on: https://github.com/mapzen/android/pull/380

Add lost docs to android page

---

theme/base.html

Use minified version of styesheet

Use minified styleguide
