mapzen/documentation

- Makefile
- config/elevation.yml
- config/matrix.yml
- config/turn-by-turn.yml
Testing out moving around the source of the Turn-by-Turn docs. Currently, it comes from mapzen-docs repo. Team wants to go back to using valhalla-docs, for now, at least. (Yes, we have some rewrites to do...)
In the [matrix-updates branch of valhalla-docs](https://github.com/valhalla/valhalla-docs/tree/matrix-help), I've moved the elevation and matrix md files into subfolders. I don't want to move the rest of the docs into folders until we have a clearer product story, to avoid having to move them again.. Merge this to master if that's easier.
In this pull request, I've tried to update the config files for turn-by-turn, elevation, and added matrix. I started on the makefile, but wasn't sure about it.
Thanks for your help, @louh.
> Change source for valhalla, elevation, matrix help files

- config/metro-extracts.yml
Metro Extracts has three md files now, index, overview (new), and walkthrough. This change adds a pages: section to the config to add a regular table of contents and the new overview topic. 
The overview is made from the content in the original blog post. Adding that info to the doc set so it can be updated more easily.
> Add pages section for new topic help

- config/elevation.yml
- config/matrix.yml
The "Edit on GitHub" link wasn't working or was pointing to the parent folder containing the docs.
Closes #92
> Update doc base URLs for Matrix and Elevation

- Makefile
- circle.yml
- config/default.yml
- config/metro-extracts.yml
- config/tangram.yml
- config/vector-tiles.yml
> Switch source location of extracts docs

- Makefile
(This replaces PR https://github.com/mapzen/mapzen-docs-generator/pull/112.)
The docs are now updated for all the missing stuff in v0.2 thru v0.7 of tiles!
More details in: https://github.com/mapzen/vector-datasource/pull/540
* Reformat entire layers.md document!
* Add overview section: data sources and attribution, name localization, geometry types, data updates, and link to changelog
* Add at least one example picture per layer (roads layer has many!)
* Add new layers from v0.2 - v0.7 (like boundaries)
* Indicate if what geometry types are included in the layer
* Detail expanded whitelist of POI, road, water, and other `kind` values per layer
* Indicate rough zoom ranges for features per layer (roads, pois)
* Update `properties` list per layer, grouping into common, common optional, and …
> update Vector Tiles doc to v0.8.0-alpha3 (again)

- config/tangram.yml
This is a proposed Tangram docs reorganization, with spaces for the upcoming Tangram Android SDK and Android Walkthroughs as well as a new Demos page.
In support of https://github.com/tangrams/tangram-docs/issues/67 and https://github.com/tangrams/tangram-docs/issues/81
To be merged in sync with https://github.com/tangrams/tangram-docs/pull/86
> reorganize Tangram docs headings

- config/tangram.yml
Looks like it's all working: https://precog.mapzen.com/mapzen/mapzen-docs-generator/tangram-android/documentation/tangram/
> Index pages for Tangram Android SDK documentation

- Makefile
- use var for Vector version
- point at v0.10 Vector release
> upgrade to Vector Tiles v0.10 docs

- docs/mapzen-services-api.md
New page to pull together rate limits and discuss functionality for the developer account dashboard. 
It needs some config work, but would likely go into a new box for getting started (for lack of a new design at the moment) on the mapzen.com/documentation page.
Please review this just in terms of content, and add comments/commits as needed.
> Add page with developer account and all rate limits

- Makefile
- config/mapzen-js.yml
- run-checklist.py
- src-index/index.md
Adds a new Maps section for Mapzen JS API documentation.
/cc @kkowalsky.
> Add Mapzen JS docs

- Makefile
- config/mapzen-js.yml
- setup-redirects.py
I’ve added a means of doing redirects in the docs.
In the mkdocs config, it looks for a section like this:
redirects:
'old-thing': 'get-started'
'offsite-stuff': 'http://example.com'
'search': 'besmirch'
The example configures three redirects: [old-thing](https://precog.mapzen.com/mapzen/mapzen-docs-generator/migurski/try-redirects/documentation/mapzen-js/old-thing) is redirected to [get-started](https://precog.mapzen.com/mapzen/mapzen-docs-generator/migurski/try-redirects/documentation/mapzen-js/get-started), [offsite-stuff](https://precog.mapzen.com/mapzen/mapzen-docs-generator/migurski/try-redirects/documentation/mapzen-js/offsite-stuff) is redirected to [http://example.com](http://example.com), and [search](https://precog.mapzen.com/mapzen/mapzen-docs-generator/migurski/try-redirects/d …
> Redirect proof of concept

- Makefile
@hanbyul-here and I have moved the documentation for Mapzen.js to a tarball generated as part of the release and deploy process.
> Updated Mapzen.js docs location to release tarball

- config/mobility.yml
With mobility in its own section, there are some lingering content issues:
- add overview topic, which used to be the main index.md file
- rename terminology to glossary, which is the style we are adopting
- rename Add routing to a map to Tutorial, which is simpler
> Mobility docs TOC - add overview + rename tutorial and glossary

- Makefile
Preview: https://precog.mapzen.com/mapzen/mapzen-docs-generator/vector-v0.10.5-doc1/documentation/vector-tiles/api-keys-and-rate-limits/
> Update prod Vector Tiles with Mapzen API keys

- config/elevation.yml
- config/metro-extracts.yml
- config/overview.yml
- run-checklist.py
They were turned off a year ago, but possibly okay now?
> Reintroduced next/prev option in Overview, Extracts, and Elevation

- Makefile
- config/addresses.yml
- config/libpostal.yml
- run-checklist.py
- src-index/index.md
fixes #207 
This adds libpostal ("address parsing") to the docs. 
It's under data for now, but perhaps we end up with a utilities subsection or something like that, as this list makes all the APIs equal...
This is a pretty minimal implementation, but gets it on the site. Preview here: https://precog.mapzen.com/mapzen/mapzen-docs-generator/rhonda-add-libpostal/documentation/
> update files for libpostal

- src-index/index.md
renaming Mapzen JS to reflect consistent naming standards as 'mapzen.js'.
> edit mapzen.js name

- Makefile
- Promote general Mapzen API key documentation instead of dup that in service docs (merges PRs from Product team.
> Update docs for vector and terrain tiles

- Makefile
- config/mobility.yml
- docs/overview/index.md
This adds the isochrone docs to the help system so we can preview and get it out there.
It puts it just as one topic under mobility, like matrix and other services.
Do not merge until service is live.
> Add isochrones and Mobility Explorer to mobility help system

- docs/overview/index.md
There was an extra ( in the markdown for the link to isochrones.
> Fix malformed link

- Makefile
- circle.yml
This implements [part 2.ii. from yesterday’s conversation](https://github.com/tilezen/vector-datasource/pull/1119#issuecomment-261404349) with @nvkelso. Both Vector Tiles and Terrain Tiles docs now come from the latest Github release, and will not require tag changes to be made here.
> Use latest official release for tiles docs

- config/search.yml
This adds the new topic for structured geocoding, which is the ability to geocode a part of an address. (To add a new file, requires changing the config in this repo.)
Note that this topic is not yet in master over in pelias-doc, so tests are failing at the moment.
cc @dianashk @trescube
> Add structured geocoding topic 

- docs/index.md
- docs/overview/index.md
We don't list the keyless limits for vector tiles, and had someone contact us about 429 errors.
From @nvkelso: 
"keylessQpd": 2400,
"keylessQpm": 120,
"keylessQps": 30,
Assuming 15 tiles / map view:
"keylessQpd": 2400, = 160 original map views per minute (unlimited cached)
"keylessQpm": 120, = 8 original map views per minute (unlimited cached)
"keylessQps": 30, = 2 original map views per second (unlimited cached)
This is good info, but I don't know what to do with it because it explains what you'd expect to see in real terms. Maybe a second paragraph on vector tiles, instead of putting it in with the other services?
> update rate limits for for vector tiles keyless access

- circle.yml
This should always have existed; not sure how we got by so long without it around. Possibly from a manual cache at some point in the distant past, and now surfaced due to CircleCI cache-busted repository rename from `mapzen-docs-generator` to `documentation`?
> Add pip install requirements.txt

- Makefile
- README.md
- circle.yml
- extract-tarball-url.py
This simplifies the usage instructions by one line.
> Replaced `jq` with a single-purpose Python script

- README.md
- SETUP.md
This integrates changes from #210 and resolves #220, which reconciles the content in the styleguide repository. I will remove/redirect the file in the styleguide to point here.
SETUP.MD is probably not the right word here, as this file is more on how to build and update docs but it's good enough for now while we do this file reorganization. 
I put the list of content sources in the readme because it seemed like the most relevant content and would help people find the doc files if they came upon this repo and thought it would have all the docs. Mostly, though, we want to direct them to mapzen.com for docs.
Fixes #220
> Update readme and setup instructions

- config/cartography.yml
The "Edit this page on GitHub" link is on the formatted docs is broken for the Cartography docs section. 
Working on precog now: https://precog.mapzen.com/mapzen/mapzen-docs-generator/rhonda-carto-repo/documentation/cartography/
> Update base URL for Cartography docs

- Makefile
- README.md
This makes the Android docs use a release, rather than a master source.
I copied the build steps for tiles, which should be done the same way, and it appears to be working: https://precog.mapzen.com/mapzen/documentation/rhonda-android-release/documentation/android/
I wasn't able to get iOS working like this because it's in a prerelease state in GitHub, but I can continue poking at GitHub's API...
cc @ecgreb - I don't think there is anything you need to do in the Android repo, other than be sure to move your docs into the release when you want them published...but we need to test!
> Change the Android docs to use a release

- docs/overview/index.md
This includes minor changes in wording based on https://mapzen.com/blog/api-keys-required/, adds sentence that API keys are required, and removes keyless rate limits. These changes can go out now to speed messaging about this.
cc @nvkelso
> Update overview to indicate that API keys are required

- docs/overview/account-settings.md
- docs/overview/billing.md
- docs/overview/rate-limits.md
All accounts now have the billing and account settings options. 
Also adds a note to the rate limits page that says when rate limits reset (previously, only on the account settings documentation page)
> Remove part of account rollout note

- config/terrain-tiles.yml
- config/vector-tiles.yml
After chatting with @nvkelso, we're going to remove the attribution and API keys and rate limits pages from both the terrain tiles and vector tiles documentation.
This PR removes them from publishing on mapzen.com and adds redirects to the top of the section (best I can do for now).
The attribution will be maintained in the repos for the open-source projects (and at mapzen.com/rights), but the API keys pages will be deleted completely because they are covered in the Mapzen docs. 
Related:
https://github.com/tilezen/vector-datasource/issues/1237
https://github.com/tilezen/vector-datasource/issues/1236
https://github.com/tilezen/joerd/issues/142
https://github.com/tilezen/joerd/issues/141
> Remove attribution and API keys pages from tiles

- config/search.yml
This removes the page about API keys, rate limits, and server caching for search. It adds in a rudimentary redirect to the top of the section (don't think it's feasible to redirect to a topic outside of this section).
Part of fixes for https://github.com/mapzen/documentation/issues/192
> Search docs: remove API keys page and add redirect

- docs/overview/rate-limits.md
mapzen.js follows the same rate limit pattern as the mobile SDKs. This adds a section for the page to clarify this.
Fixes https://github.com/mapzen/mapzen.js/issues/202 over in the mapzen.js repo.
> Add rate limits section for mapzen.js

- config/mobility.yml
This adds the Mobility Explorer tutorial to the help system. 
Depends on https://github.com/valhalla/valhalla-docs/pull/168 being merged first.
> Add Mobility Explorer tutorial to table of contents

- docs/overview/account-settings.md
- docs/overview/billing.md
- docs/overview/support.md
NOTE: This should not be merged until the functionality is on the production server.
This adds a section for enabling premium support in your account settings and replaces any use of "contact us" to buy it. It also adds links to the pricing page, which lists the fee. @souperneon, please have a look! I've generally used "enable" and "disable", but added a few other synonyms because people might think of those terms, too. 
I've also added some language about whether paid support includes on-premises installation help, given some questions about that recently. @mjcunningham, see if that's reasonable to include.
> [Do not merge yet] Add premium support section and updates

- docs/overview/rate-limits.md
These were missing from the rate limits page (a user asked about it), so this adds in the current numbers for when an API key is included with a request.
> Add libpostal API rate limits

- config/search.yml
This adds a new file about language support to the published search help on mapzen.com.
cc @dianashk @missinglink
> Add language codes topic to search help

- config/mobility.yml
- docs/overview/rate-limits.md
This adds map matching API reference and Mobility Explorer topics to the help. It also adds the rate limits to the page with the others.
This replaces https://github.com/mapzen/documentation/pull/279, which had gotten pretty out of date.
Do not merge until ready for release.
> Add map-matching topics to help for release

- docs/overview/account-settings.md
Users can now delete their Mapzen accounts on their own (self-service). This adds documentation to cover how to do it.
@sleepylemur - Thank you for adding this functionality!
> Add section on how to delete your Mapzen account

- config/search.yml
Something has gone wrong with this redirect.
This makes it go to a 404 for now, rather than show old content.
> Removing the api keys redirect for old search topic

- config/search.yml
From the files of "DUH"
Fixes #326 
Sometimes .md needs to be there, other times not. This one is a not.
> removing .md to see if it fixes redirects

- docs/overview/rate-limits.md
Libpostal and Mapzen Places (WoF) have updated limits, effective October 1, 2017. Do not merge until then.
This updates the doc for those limits, as well as fixes some inconsistencies on the page.
> Update libpostal and mapzen places rate limits

- docs/overview/api-keys.md
This adds a section to the docs on how to protect your API key by importing a key from a separate file.
Seemed better to talk about it like this instead of defining the global in the same scene file. I think this is how you do it, but @meetar @burritojustice, have a look!
> Add how to import a YAML for API key protection

- config/mobility.yml
This adds a new file to the table of contents that discusses how speeds are calculated in the mobility APIs.
This nests under a new heading of Reference, along with decoding and any other related new docs. Nesting like this does not affect the URL, so no redirects are needed for the existing decoding topic.
Preview: https://precog.mapzen.com/mapzen/documentation/rhonda-mobility-speed/documentation/mobility/speeds/
cc @dnesbitt61 - thanks for the docs!
> Add new speed documentation to mobility help

- Makefile
- config/mobility.yml
Moved a bunch of mobility documentation around, which means we no longer need to add URL redirects and things at build time.
Depends on https://github.com/valhalla/valhalla-docs/issues/127 to be merged first.
Also must remove the changes to the makefile when this is in valhalla master.
> Update build process to reflect reorganized mobility content
